### ISSUE TITLE
Document why it's forked from webfeed

### ISSUE THREAD

**Issue by matthew-carroll** [sudame/dart-rss#18] opened 2022-10-15 23:01 UTC
Hi, I'm looking for an RSS parser and serializer. I found `webfeed` and this package. The description for this package says it's forked from `webfeed`, but doesn't specify why it needed to be forked.

Can you let me know the purpose for the fork, and how you see these two packages evolving independently over time? Also, you might consider adding that information to the README.

**Comment by matthew-carroll** [comment] 2022-11-23 04:01
Any update on this?

**Comment by amugofjava** [comment] 2022-12-23 14:14
This project has not been touched in months. Would you consider adding other maintainers to the project so that it can continue?

**Comment by amugofjava** [comment] 2023-05-07 12:38
@matthew-carroll From what I remember from the author, this fork came about because the development of webfeed stopped; however, this fork has not been touched for a long time. Did you manage to find another RSS parser? Thanks.

**Comment by matthew-carroll** [comment] 2023-05-07 19:32
@amugofjava - No, I never found another one. If this is something the community needs, and there are any companies that would like to help fund it, we could create a new project over the Flutter Bounty Hunters.

**Comment by sudame** [comment] 2023-06-22 22:15
@matthew-carroll @amugofjava 
Sorry for the late reply.

I actually stopped writing Flutter already, so maintaining this project has become less of a priority for me. I am considering archiving this project. If necessary, I encourage you to fork this project and maintain it anew or use another project.

Thanks.

**Comment by matthew-carroll** [comment] 2023-06-22 22:42
@sudame is there any reason that you don't want to transfer the repo and the Pub listing? You have one of the most discoverable names on Pub, and no one else can use it: https://pub.dev/packages/dart_rss

If you transfer this repo to the Flutter Bounty Hunters, we'll maintain it.

https://github.com/flutter-Bounty-Hunters

https://pub.dev/publishers/flutterbountyhunters.com/packages

**Comment by sudame** [comment] 2023-06-22 22:48
@matthew-carroll  If Flutter Bounty Hunters would be willing to maintain this project, I would love to do so! How should I deal with this?

**Comment by matthew-carroll** [comment] 2023-06-22 22:50
@sudame there will be two steps. One on GitHub, and one on Pub.

On the GitHub side, you can go to the project settings for this repo and in there you'll find a button to transfer the repo. Enter the GitHub name for the Flutter Bounty Hunters, and initiate the transfer. I'll accept on my end.

On Pub, go to the "Admin" pane for your package. On that page there will be an option to transfer to a Publisher. Once again, select the Flutter Bounty Hunters.

That should be all that you need to do.

**Comment by sudame** [comment] 2023-06-22 22:53
@matthew-carroll Thanks. Am I allowed to start these steps right away?

**Comment by matthew-carroll** [comment] 2023-06-22 22:53
Yeah, whenever you're ready.

**Comment by sudame** [comment] 2023-06-22 23:02
@matthew-carroll 

According to the GitHub documentation, I must have permission to create repositories if I want to transfer repositories to an organization.

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.
> https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#about-repository-transfers

I'm thinking of taking the method of transferring the repository to your personal account once and then you transfer it to the organization's repository.

**Comment by matthew-carroll** [comment] 2023-06-22 23:05
> I'm thinking of taking the method of transferring the repository to your personal account once and then you transfer it to the organization's repository.

I think that's a good idea. If you transfer to me, I'll forward it to the organization.

**Comment by sudame** [comment] 2023-06-22 23:14
@matthew-carroll OK. The same thing is happening on the Pub side. I am not a member of Flutter Bounty Hunters publisher, so I could not transfer the package.

Can you temporarily add `suda.mikihiro@gmail.com` (this email address is published on https://github.com/sudame) as a member of Flutter Bounty Hunters publisher? You can remove me once the transfer is complete.

**Comment by matthew-carroll** [comment] 2023-06-22 23:26
Sure. I just added you to Pub.

**Comment by matthew-carroll** [comment] 2023-06-22 23:36
Thanks for transferring. I removed your access now that it looks like it's transferred.

Any luck on the GitHub side?

**Comment by sudame** [comment] 2023-06-22 23:36
Thanks! I just requested to transfer the ownership on both Pub and GitHub :tada:

**Comment by sudame** [comment] 2023-06-22 23:38
@matthew-carroll, I have confirmed that I was able to transfer both successfully. Thank you so much.

**Comment by matthew-carroll** [comment] 2023-06-22 23:39
Thanks. Both transfers are complete. My team will begin upgrading this repo as we have time.

Thanks for helping to preserve the project and the Pub listing. I think this is what's best for the community.

**Closed as completed** 2023-06-23 00:00 UTC
